version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ecommerce_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: nest_ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
